version: '3'  # version of compose format

services:
  apache:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'php:8.0.28-apache'
    container_name: php_audio_video
    restart: always
    volumes:
      - ./:/var/www/html # mount
      - ./_DockerConfig/php.ini:/usr/local/etc/php/php.ini
    ports:
      - '8010:80' # host:container
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: mysql_audio_video
    image: mysql:5.7.42
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: sandbox_user
      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3318:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
